// demos/vite-solid/src/Button.tsx
import type { ComponentProps } from 'solid-js';
import { css } from '@acab/ecsstatic';

export const Button = (props: ComponentProps<'button'>) => (
  <button class={button} {...props} />
);

const button = css`
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
  display: inline-grid;
  place-items: center;

  @media (prefers-color-scheme: light) {
    background-color: #f9f9f9;
  }

  &:hover {
    border-color: #a93c3c;
  }

  &:focus {
    outline-width: 4px;
  }

  &:disabled {
    opacity: 0.5;
  }
`;

// demos/vite/src/Button.tsx
import * as React from 'react';
import { scss } from '@acab/ecsstatic';

export default (props: React.ComponentProps<'button'>) => {
	return <button className={button} {...props} />;
};

const button = scss`
	@use 'open-props-scss' as op;

	all: unset;
	font: inherit;
	color: op.$purple-9;
	border: 1px solid;
	border-radius: 4px;
	padding: 0.5rem 1rem;
	transition: color 0.2s;

	&:hover {
		color: op.$purple-6;
	}
`;
